[server]
fileWatcherType = "none"

[[pages]]
path = "app/about.py"
name = "Home"
icon = "ğŸ¾"

[[pages]]
path = "app/ingest_ui.py"
name = "Ingestion Pipeline"
icon = "ğŸš€"

[[pages]]
path = "core/validate.py"
name = "Validation"
icon = "âœï¸"

[[pages]]
path = "app/species_detection_ui.py"
name = "Species Detection"
icon = "ğŸ§¬"

[[pages]]
name = "Analysis"
icon = ""
is_section = true

[[pages]]
path = "app/analysis_ui.py"
name = "Analysis Explorer"
icon = "ğŸ“Š"

[[pages]]
path = "app/semantic_search_ui.py"
name = "Exploration / Search"
icon = "ğŸ”"

[[pages]]
name = "Tools"
icon = ""
is_section = true

[[pages]]
path = "tools/adhoc_scraper.py"
name = "One-Off Species Scraper"
icon = "ğŸ› ï¸"

[[pages]]
path = "tools/reset.py"
name = "Database & File Clean-up"
icon = "ğŸ§¹"

[[pages]]
path = "tools/geocode_image_locations.py"
name = "Geocode & Update Image Locations"
icon = "ğŸ—ºï¸"

[[pages]]
path = "app/regenerate_embeddings_ui.py"
name = "Regenerate Image Embeddings"
icon = "ğŸ”"

[[pages]]
path = "tools/regenerate_text_embeddings.py"
name = "Regenerate Text Embeddings"
icon = "ğŸ”"

[[pages]]
name = "Appendix"
icon = ""
is_section = true

[[pages]]
path = "appendix/project.py"
name = "Project Overview"
icon = "ğŸ“–"

[[pages]]
path = "appendix/workflow.py"
name = "Complete Wildlife Image Processing Workflow"
icon = "ğŸ“–"

[[pages]]
path = "appendix/references.py"
name = "References"
icon = "ğŸ“–"

